name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Angular (prerender)
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Disable S3 Block Public Access (bucket)
        run: |
          aws s3api put-public-access-block --bucket creditaria-chimal --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

      - name: Ensure public-read bucket policy
        run: |
          cat > bucket-policy.json << 'EOF'
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::creditaria-chimal/*"
              }
            ]
          }
          EOF
          aws s3api put-bucket-policy --bucket creditaria-chimal --policy file://bucket-policy.json


      - name: Sync to S3 (AWS CLI)
        run: aws s3 sync dist/chimal-ui/browser s3://creditaria-chimal --delete

      - name: Set ACL public-read on uploaded objects
        run: |
          aws s3 sync dist/chimal-ui/browser s3://creditaria-chimal --delete --acl public-read


      - name: Invalidate CloudFront (AWS CLI)
        run: aws cloudfront create-invalidation --distribution-id EVOCES3Z59HEJ --paths "/*"

